### ISSUE TITLE
Crash with elven avatar bonemealing grass block

### ISSUE THREAD

**Issue by bluegreen1024** [Luicuelo/botaunomy#1]
I placed an elven avatar with a hopper behind it containing bonemeal and a grass block in front of it, and (foolishly perhaps) I did NOT give the avatar a Rod of Will (or a Rod of Toil). Attached is the crash report. Note that this was in a heavily modded environment; I will see if I can reproduce the bug with fewer mods present when I get the chance.

OS: Windows 11
Forge:  14.23.5.2860
Botania: r1.10-364.4
Botaunomy Reloded: 0.3.8
[crash-2022-05-10_22.00.17-server.txt](https://github.com/Luicuelo/botaunomy/files/8694055/crash-2022-05-10_22.00.17-server.txt)

**Comment by Luicuelo** [comment]
I compiled version 0.3.9 which I hope will fix the bug. You can get it from the jar folder here on github.
Please give me your feeback about  if it was fixed.
Thanks for your help
