### ISSUE TITLE
Sleep message appears even when config option is set to false

### ISSUE THREAD

**Issue by yurifel** [Luicuelo/botaunomy#2]
### Issue Description

Sleep message appears even when config option is set to false.

### Steps to Reproduce

1. Create new Forge instance.
2. Install Botania, Baubles, & Botaunomy Reloaded
3. Create new world
4. Set time to night

### Forge Version

14.23.5.2860

### Mod Versions

Botania r1.10-364.4
Baubles 1.12-1.5.2
Botaunomy Reloaded 1.12.2-0.3.9

### Logs

https://gist.github.com/yurifel/3fc5711fcb6e024d3a3c9a4904f0ab9b

**Comment by Luicuelo** [comment]
I have tried to reproduce the bug but it is working fine.

Please download the latest version from curseforge, I think that this problem is already solved in the version that is now online.


There is an "if" just before sending the message that depends on the value read in the config

                   if(Config.asleepMessage) {                   
	                   for(EntityPlayer p:listReal) {                	  
	                	   p.sendMessage(text);
	                   }
                   }

**Comment by Luicuelo** [comment]
Indeed, the last version uploaded to curseforge was not the correct one. I have uploaded it again, thank you very much for your contribution.
